language: java
sudo: required
dist: trusty
jdk:
  - openjdk8
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -yq
  - sudo apt-get install -y python3.5
  - sudo apt-get install -y python3-setuptools python3-pip
  - sudo apt-get install -y awscli
  - eval "$(gimme 1.8.3)"
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
  - sudo pip install awscli
install: skip
script:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      frameworks/kafka/build.sh aws;
    else
      frameworks/kafka/build.sh;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
